from . import menu_uchun
from . import taomlar_uchun
from . import ichimliklar_uchun
from . import shirinliklar_uchun
from . import fast_food_uchun
from . import eng_uchun
from . import taomlar_uchun2
from . import ichimliklar_uchun2
from . import shirinliklar_uchun2
from . import fast_food_uchun2